inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

RSpec/VerifiedDoubles:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleDescribes:
  Enabled: false
