platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
    path: src
  - name: app-terraform-outputs
  - name: task-definition-arn
  - name: run-task-command
    optional: true
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN:
  APPLICATION:
  CLUSTER: task_runner
  COMMAND: # Place command in run-task-command file or use COMMAND param
  VARIANT:
  DISABLE: false
  LOG_TO_SPLUNK: true
run:
  path: ./src/concourse/tasks/run-task.sh
