platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
    path: src
  - name: app-terraform-outputs
  - name: task-definition-arn
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
  APPLICATION:
  CLUSTER: task_runner
  COMMAND:
  VARIANT:
  SKIP_DB_MIGRATIONS:
run:
  path: ./src/concourse/tasks/run-task.sh
