platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/awscli
    tag: latest # TODO - manage image versions ourselves instead of using latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
    path: src
  - name: app-image
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
  IMAGE_ASSETS_PATH:
  S3_BUCKET_PATH_PATTERN:
  WORKSPACE:
run:
  path: ./src/concourse/tasks/upload-rails-assets.sh
