name: linting
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.6
          terraform_wrapper: false

      - name: get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: cache terraform plugins
        uses: actions/cache@v2
        env:
          cache-name: cache-terraform-plugins
        with:
          path: ~/.terraform/plugin-cache
          key:
            ${{ env.cache-name }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('terraform/deployments/**/main.tf', 'terraform/deployments/**/.terraform.lock.hcl', 'terraform/deployments/**/versions.tf') }}

      - name: terraform fmt
        working-directory: terraform
        run: |
          if ! terraform fmt -write=false -diff=true -list=true -recursive -check .
          then
            >&2 echo "Some terraform files weren't formatted correctly. Run 'terraform fmt' to fix them."
            exit 1
          fi

      - name: rspec
        run: |
          bundle install
          rspec

      - name: terraform validate
        working-directory: terraform
        env:
          TF_IN_AUTOMATION: true
        run: |
          export TF_PLUGIN_CACHE_DIR=~/.terraform/plugin-cache
          mkdir -p "$TF_PLUGIN_CACHE_DIR"

          shopt -s globstar

          for f in deployments/**/main.tf; do
            d=$(dirname "$f")
            (
              echo "$d"
              cd "$d"
              terraform init -backend=false
              terraform validate
              echo -e '\n-------------------------\n'
            )
          done

      - name: run tflint
        env:
          TFLINT_VERSION: v0.24.1
          TFLINT_RULESET_WORKSPACES_VERSION: 0.2.0
        run: |
          TEMP_PATH="$(mktemp -d)"
          PATH="${TEMP_PATH}:$PATH"
          curl --silent --fail -L "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip && unzip tflint.zip -d "${TEMP_PATH}" && rm tflint.zip
          curl --silent --fail -L "https://github.com/richardTowers/tflint-ruleset-workspaces/releases/download/${TFLINT_RULESET_WORKSPACES_VERSION}/tflint-ruleset-workspaces-linux" -o tflint-ruleset-workspaces
          chmod +x tflint-ruleset-workspaces
          mkdir -p ~/.tflint.d/plugins
          mv tflint-ruleset-workspaces ~/.tflint.d/plugins

          for f in terraform/deployments/*/.tflint.hcl; do
            d=$(dirname "$f")
            (
              echo "$d"
              cd "$d"
              terraform init -backend=false
              TF_WORKSPACE=example_workspace tflint --module .
              echo -e '\n-------------------------\n'
            )
          done

